const state = {
  wizards: {},
  nextId: 1,
  selectedWizardId: null,
  selectedAction: 'move',
  animating: false,
  turnCount: 1,
  currentTurn: 'player',
  firstPlayerTurnDone: false,
  firstEnemyTurnDone: false,
  gameOverResult: null,
  placingWizardId: null,
  trails: {},
  mountains: {},
  tempMountains: {},
  water: {},
  voids: {},
  portals: {},
  nexuses: { player: [], enemy: [] },
  playerTeam: [],
  enemyTeam: [],
  playerLoadout: [],
  enemyLoadout: [],
  mana: 0,
  maxMana: 0,
  enemyMana: 0,
  enemyMaxMana: 0,
  seed: 1,
  rng: null,
  log: [],
  fxEnabled: true,
  matchId: 0,
  aiBrain: 'hunter',
  gameMode: 'defense'
};
